# Generated by Django 4.0.6 on 2022-07-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('fechaNacimiento', models.DateField(max_length=40)),
                ('parentesco', models.CharField(max_length=30)),
                ('dni', models.IntegerField()),
            ],
        ),
    ]
